###Pruebas del API
###

### 
POST http://localhost:8080/api/toneAnalyzer
Content-Type: application/json

{
    "toneInput": { 
        "text": "I am a sad person because my friend Dong does not want to see may code"
        }, 
    "contentLanguage": "EN"
}